# Generated by Django 3.2.9 on 2021-11-02 13:56

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Category_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='tbl_advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('company_id', models.IntegerField()),
                ('buddy_list', models.CharField(default='[]', max_length=300)),
                ('caller_response_template', models.CharField(default='', max_length=1000)),
                ('advisor_response_template', models.CharField(default='', max_length=1000)),
                ('caller_text_response_template', models.CharField(default='', max_length=1000)),
                ('manager_response_template', models.CharField(default='', max_length=1000)),
                ('bookingURL', models.URLField(default='', max_length=5000)),
                ('configEscalationOnOff', models.BooleanField(default=False)),
                ('filterMeetingOnOff', models.BooleanField(default=False)),
                ('promptMeetingOptions', models.CharField(default='', max_length=50)),
                ('filterVMOnOff', models.BooleanField(default=False)),
                ('confAskPermissionToText', models.BooleanField(default=False)),
                ('configTimeoutVM', models.IntegerField(default=0)),
                ('configTimeoutNoVMLeft', models.IntegerField(default=0)),
                ('promptGreeting', models.CharField(default='', max_length=1000)),
                ('promptMeetingConclusion', models.CharField(default='', max_length=200)),
                ('promptVMOptions', models.CharField(default='', max_length=200)),
                ('promptVMStart', models.CharField(default='', max_length=200)),
                ('promptVMPermission', models.CharField(default='', max_length=200)),
                ('promptVMConclusion', models.CharField(default='', max_length=200)),
                ('promptFirstName', models.CharField(default='', max_length=100)),
                ('callerMeetingTemplate', models.CharField(default='', max_length=1000)),
                ('advisorMeetingTemplate', models.CharField(default='', max_length=1000)),
                ('includeRecording', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('open_weekly_from', models.CharField(max_length=20)),
                ('open_weekly_to', models.CharField(max_length=20)),
                ('open_sat_from', models.CharField(max_length=20)),
                ('open_sat_to', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(default='', max_length=50)),
                ('twilio_account_sid', models.CharField(max_length=100)),
                ('twilio_auth_token', models.CharField(max_length=100)),
                ('twilio_phone_number', models.CharField(max_length=100)),
                ('customerInfoAPI', models.URLField(default='', max_length=1000)),
                ('fallbackForwardTo', models.CharField(default='', max_length=100)),
                ('unregisteredForwardTo', models.CharField(default='', max_length=100)),
                ('unregisteredEmailTo', models.EmailField(default='', max_length=200)),
                ('unregisteredSmsTo', models.CharField(default='', max_length=100)),
                ('unregisteredAPICall', models.URLField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_voicemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('caller_phone', models.CharField(max_length=30)),
                ('advisor_phone', models.CharField(max_length=30)),
                ('caller_name', models.CharField(max_length=50)),
                ('ok_text', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=1)),
                ('delay_time', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('alert_to_manager', models.IntegerField(default=0)),
                ('replier_id', models.IntegerField(default=-1)),
                ('flag', models.IntegerField(default=0)),
                ('caller_replied', models.IntegerField(default=0)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_voicemail_response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_id', models.IntegerField()),
                ('replier_name', models.CharField(max_length=50)),
                ('message', models.CharField(default='', max_length=1024)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uid', models.BigIntegerField(default=0)),
                ('s_password', models.CharField(default='', max_length=255)),
                ('phone_number', models.CharField(default='', max_length=30)),
                ('company_id', models.IntegerField(default=0)),
                ('agents', models.CharField(default='', max_length=1024)),
                ('advisors', models.CharField(default='', max_length=1024)),
                ('reports', models.CharField(default='[]', max_length=4096)),
                ('factor_booked', models.FloatField(default=1)),
                ('factor_transfer', models.FloatField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
